language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

env:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=4.7.5 WP_MULTISITE=0
  - WP_VERSION=4.6.6 WP_MULTISITE=0
  - WP_VERSION=4.5.9 WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1
  - WP_VERSION=4.7.5 WP_MULTISITE=1
  - WP_VERSION=4.6.6 WP_MULTISITE=1
  - WP_VERSION=4.5.9 WP_MULTISITE=1

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

before_script:
  - source tests/bin/setup.sh

script: phpunit

dist: trusty